# Numpy


In [1]:
import numpy as np

In [2]:
np1 = np.array([10,20,30,40,50,60,70]),        #array lists
np2 = np.array(['orange','mango','apple']),
np3 = np.array([1,'data'])

In [3]:
print(np1)
print(np2)
print(np3)

(array([10, 20, 30, 40, 50, 60, 70]),)
(array(['orange', 'mango', 'apple'], dtype='<U6'),)
['1' 'data']


In [4]:
type(np1),(np2),(np3)

(tuple,
 (array(['orange', 'mango', 'apple'], dtype='<U6'),),
 array(['1', 'data'], dtype='<U11'))

In [5]:
mat1 = np.array([['a','b','c'],['d','f','g']]) #creating 2 dimensional string array list 

In [6]:
mat1

array([['a', 'b', 'c'],
       ['d', 'f', 'g']], dtype='<U1')

In [7]:
np1.count

<function tuple.count(value, /)>

In [8]:
mat1.shape

(2, 3)

In [9]:
mat1.dtype

dtype('<U1')

In [10]:
print(np1.dtype)
print(np2.dtype)
print(np3.dtype)



AttributeError: 'tuple' object has no attribute 'dtype'

In [ ]:
mat1[0,0] = 11

In [ ]:
mat1

array([['1', 'b', 'c'],
       ['d', 'f', 'g']], dtype='<U1')

In [ ]:
#mat1[(0,2)] = "text"
mat=np.zeros((3,3))


In [ ]:
mat

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
mat[0,0]=11

In [ ]:
mat

array([[11.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [ ]:

arr3 = np.ones((3,2))

In [ ]:
arr3

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
mat2 = np.arange(1,50,2)  #range betwwen 1 to 50 divided by 2

In [ ]:
mat2

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

In [ ]:
mat3 = np.linspace(1,25,50)

In [ ]:
mat3

array([ 1.        ,  1.48979592,  1.97959184,  2.46938776,  2.95918367,
        3.44897959,  3.93877551,  4.42857143,  4.91836735,  5.40816327,
        5.89795918,  6.3877551 ,  6.87755102,  7.36734694,  7.85714286,
        8.34693878,  8.83673469,  9.32653061,  9.81632653, 10.30612245,
       10.79591837, 11.28571429, 11.7755102 , 12.26530612, 12.75510204,
       13.24489796, 13.73469388, 14.2244898 , 14.71428571, 15.20408163,
       15.69387755, 16.18367347, 16.67346939, 17.16326531, 17.65306122,
       18.14285714, 18.63265306, 19.12244898, 19.6122449 , 20.10204082,
       20.59183673, 21.08163265, 21.57142857, 22.06122449, 22.55102041,
       23.04081633, 23.53061224, 24.02040816, 24.51020408, 25.        ])

In [ ]:
mat3.shape

(50,)

In [ ]:
mat4 = np.random.rand(5,10)

In [ ]:
mat4

array([[0.90284399, 0.6801615 , 0.31713137, 0.49677651, 0.3152719 ,
        0.11723449, 0.47842384, 0.21728079, 0.9423657 , 0.19790123],
       [0.44528552, 0.53061419, 0.37267555, 0.8032365 , 0.06319804,
        0.84792023, 0.51944321, 0.1397127 , 0.62779935, 0.15488218],
       [0.72607809, 0.90973333, 0.96613283, 0.19827928, 0.70942833,
        0.57824471, 0.01504302, 0.17190472, 0.12765565, 0.38269848],
       [0.59768664, 0.49482361, 0.5148999 , 0.41399   , 0.01114643,
        0.96746745, 0.51088352, 0.31049543, 0.23129802, 0.16174367],
       [0.56907639, 0.78135076, 0.33275695, 0.58523074, 0.11021488,
        0.21959409, 0.14747382, 0.90447849, 0.3120674 , 0.85474528]])

In [ ]:
mat5= np.random.randn(5,5)

In [ ]:
mat5

array([[ 0.34061269, -0.82553864, -1.11075627, -0.98037315, -0.78329374],
       [ 1.38676035, -0.39897838,  0.98303428, -0.78147991,  0.52044426],
       [ 1.25010956,  0.2040871 , -0.13919717, -0.00916772, -0.97129611],
       [-0.53288334, -0.06928201,  0.85372679, -0.59430896,  0.27354786],
       [-0.33687454,  1.36659509,  0.18268374,  0.30735796,  0.65618153]])

In [ ]:
mat5[0,0]

11.0

In [ ]:
mat5[0,1]

-0.825538644316926

In [ ]:
mat5[0:5]

array([[ 1.10000000e+01, -8.25538644e-01, -1.11075627e+00,
        -9.80373150e-01, -7.83293741e-01],
       [ 1.38676035e+00, -3.98978381e-01,  9.83034279e-01,
        -7.81479910e-01,  5.20444261e-01],
       [ 1.25010956e+00,  2.04087097e-01, -1.39197169e-01,
        -9.16771868e-03, -9.71296107e-01],
       [-5.32883338e-01, -6.92820053e-02,  8.53726788e-01,
        -5.94308964e-01,  2.73547862e-01],
       [-3.36874543e-01,  1.36659509e+00,  1.82683737e-01,
         3.07357965e-01,  6.56181535e-01]])

In [ ]:
mat5[0:3,:]

array([[ 1.10000000e+01, -8.25538644e-01, -1.11075627e+00,
        -9.80373150e-01, -7.83293741e-01],
       [ 1.38676035e+00, -3.98978381e-01,  9.83034279e-01,
        -7.81479910e-01,  5.20444261e-01],
       [ 1.25010956e+00,  2.04087097e-01, -1.39197169e-01,
        -9.16771868e-03, -9.71296107e-01]])

In [ ]:
mat5[0:3,1:2]

array([[-0.82553864],
       [-0.39897838],
       [ 0.2040871 ]])

In [ ]:
mat5

array([[ 1.10000000e+01, -8.25538644e-01, -1.11075627e+00,
        -9.80373150e-01, -7.83293741e-01],
       [ 1.38676035e+00, -3.98978381e-01,  9.83034279e-01,
        -7.81479910e-01,  5.20444261e-01],
       [ 1.25010956e+00,  2.04087097e-01, -1.39197169e-01,
        -9.16771868e-03, -9.71296107e-01],
       [-5.32883338e-01, -6.92820053e-02,  8.53726788e-01,
        -5.94308964e-01,  2.73547862e-01],
       [-3.36874543e-01,  1.36659509e+00,  1.82683737e-01,
         3.07357965e-01,  6.56181535e-01]])

# **Numpy**

##  Array Creation

- `np.array`: Creates a NumPy array, which is a multi-dimensional, homogeneous data structure that can hold various types of elements.



In [ ]:
import numpy as np

# Create a array
arr = np.array([10,20,30,40,50,60])
print("NumPy Array:", arr)

NumPy Array: [10 20 30 40 50 60]


- `np.zeros`: Generates an array filled with zeros of a specified shape.


In [ ]:
# Create an array of zeros
zeros_arr = np.zeros((5, 3))  # 5 rows, 3 columns
print("Zeros_Array:")
print(zeros_arr)

Zeros_Array:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]



- `np.ones`: Creates an array filled with ones of a specified shape.


In [ ]:
# Create an array of ones
ones_arr = np.ones((3, 3))  # 3 rows, 3 columns
print("Ones_Array:")
print(ones_arr)

Ones_Array:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


- `np.random.rand`: Generates random numbers in a specified shape from a uniform distribution over [0, 1).


In [ ]:
# Generate random numbers between 0 and 1
random_arr = np.random.rand(2, 5)  # 3 rows, 2 columns
print("Random_Array:")
print(random_arr)


Random_Array:
[[0.03664534 0.69487109 0.28804553 0.66212315 0.01538128]
 [0.87764416 0.02702201 0.6935926  0.11398822 0.31045797]]


**. Array Operations**

In [ ]:
# Create two arrays
arr1 = np.array([10, 20, 30])
arr2 = np.array([40, 50, 60])

- `np.add`: Element-wise addition of two arrays or a scalar and an array.

In [ ]:
 # element wise addition

add_result = np.add(arr1,arr2)
print('Addition_Result:',add_result)


Addition_Result: [50 70 90]


- `np.subtract`: Element-wise subtraction of one array from another or a scalar from an array.


In [ ]:
#  element wise subtraction
subtract_result = np.subtract(arr2,arr1)
print('Substraction_Result:',subtract_result)

Substraction_Result: [30 30 30]


- `np.multiply`: Element-wise multiplication of two arrays or a scalar and an array.

https://numpy.org/doc/stable/reference/generated/numpy.multiply.html

In [ ]:
# Perform element-wise multiplication
multiply_result=np.multiply(arr1,arr2)
print('Multiplication_Result:',multiply_result)


Multiplication_Result: [ 400 1000 1800]


- `np.divide`: Element-wise division of one array by another or a scalar by an array.



In [ ]:
# element wise division
divide_result=np.divide(arr1,arr2)
print('Division_Reult:',divide_result)

Division_Reult: [0.25 0.4  0.5 ]


- `np.sqrt`: Computes the element-wise square root & square of an array.


In [ ]:
# Compute element-wise square root
arSq = np.array([2,4,6])
sqr_result = np.square(arSq)
print("Square  Result:", sqr_result)
arr_sq = np.array([5,10,15])
sqrt_result=np.sqrt(arr_sq)
print('Square_Root_Result:',sqrt_result)

Square  Result: [ 4 16 36]
Square_Root_Result: [2.23606798 3.16227766 3.87298335]


In [ ]:
# Create a 2D array
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [ ]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

- `ndarray.shape`: Returns a tuple representing the dimensions of the array.


In [ ]:
# Get the shape of the array
shape = arr.shape
print("Array Shape:", shape)

Array Shape: (2, 3)


- `ndarray.size`: Returns the total number of elements in the arra

In [ ]:
# Get the total number of elements
size =arr.size
print("Array Size:", size)

Array Size: 6


- `ndarray.ndim`: Returns the number of dimensions (axes) of the array.

https://numpy.org/doc/stable/reference/generated/numpy.ndarray.ndim.html

In [ ]:
array_num=np.array([1,2,3])

In [ ]:
# Get the number of dimensions
ndim = arr.ndim
print("Number of Dimensions:", ndim)

Number of Dimensions: 2


- `ndarray.dtype`: Returns the data type of the elements in the array.

In [ ]:
# write data type of the elements
dtype = array_num.dtype
print("Data Type:", dtype)

Data Type: int32


- Indexing (`ndarray[index]`): Allows you to access a specific element in a NumPy ndarray using its index value. The index can be an integer or a tuple of integers for multidimensional arrays.


In [ ]:
# Create a 1D array
arr_1d = np.array([1, 2, 3, 4, 5])

# Indexing: Access a specific element
element = arr_1d[1]  # Access the element at index 2 (3rd element)
print("Indexed Element:", element)

# Create a 2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Indexing: Access an element in a 2D array
element_2d = arr_2d[0, 2]  # Access the element at row 1, column 2 (6)
print("Indexed 2D Element:", element_2d)

arr_3d = np.array([[[3,4],[5,6],[7,8]]])

element_3d = arr_3d[0,1]
print("Indexed 3d elementy", element_3d)



Indexed Element: 2
Indexed 2D Element: 3
Indexed 3d elementy [5 6]


- Slicing (`ndarray[start:end]`): Allows you to extract a portion of a NumPy ndarray using a range of indices. The `start` index is inclusive, and the `end` index is exclusive. This creates a new ndarray that contains the specified slice of elements.

In [ ]:
sliced_1d=arr_1d[0:3]
print('Slice1c:',sliced_1d)

sliced_2d=arr_2d[0:2,1:2]
print('sliced2d:',sliced_2d)

Slice1c: [1 2 3]
sliced2d: [[2]
 [5]]


In [ ]:
# Slicing: Extract a portion of a 1D array
sliced_1d = arr_1d[0:4]  # Extract elements from index 1 to 3 (exclusive)
print("Sliced 1D Array:", sliced_1d)

# Slicing: Extract a portion of a 2D array
sliced_2d = arr_2d[0:2, 1:3]  # Extract rows 0 to 1 and columns 1 to 2
print("Sliced 2D Array:")
print(sliced_2d)

Sliced 1D Array: [2 3 4]
Sliced 2D Array:
[[2 3]
 [5 6]]


5. Aggregation and Statistics:

- `np.sum`: Computes the sum of array elements along a specified axis or over the entire array.

In [ ]:
# Create a 1D array
arr = np.array([4, 2, 9, 5, 1, 8, 6, 3, 7])

arr_sum=np.array([8,6,-2,50,-4,7,1])

# Compute the sum of array elements
sum_result = np.sum(arr)
print("Sum:", sum_result)

sum_result = np.sum(arr_sum)
print('sum_1:',sum_result)

Sum: 45
sum_1: 66


- `np.mean`: Calculates the mean (average) of array elements along a specified axis or over the entire array.


In [ ]:
# Calculate the mean of array elements
mean_result = np.mean(arr_sum)
print("Mean:", mean_result)

mean_example=np.array([100,50,60,30])

mean_result=np.mean(mean_example)
print('mean_1:',mean_result)

Mean: 9.428571428571429
mean_1: 60.0


- `np.median`: Computes the median (middle value) of array elements along a specified axis or over the entire array.

In [ ]:
# Calculate the median of array elements
median_result = np.median(arr)
print("Median:", median_result)

median_result=np.median(mean_example)
print('median :',median_result)

Median: 5.0
median : 55.0


- `np.std`: Calculates the standard deviation of array elements along a specified axis or over the entire array.


In [ ]:
# Calculate the standard deviation of array elements
std_result = np.std(arr)
print("Standard Deviation:", std_result)

std_example=np.array([10,20,30,40,50])

std_result=np.std(std_example)
print('Standard_deviation:',std_result)

Standard Deviation: 2.581988897471611
Standard_deviation: 14.142135623730951


- `np.min`: Finds the minimum value among array elements along a specified axis or over the entire array.


In [ ]:
# Find the minimum value in the array
min_result = np.min(arr)
print("Minimum:", min_result)

min_exampl=np.array([70,60,50,700,30])
min_result=np.min(min_exampl)
print('Min_Value:',min_result)

Minimum: 1
Min_Value: 30


- `np.max`: Finds the maximum value among array elements along a specified axis or over the entire array.

In [ ]:
# Find the maximum value in the array
max_result = np.max(arr)
print("Maximum:", max_result)

max_example=np.array([1000,1111,200,30])
max_result=np.max(max_example)
print('Max_value:',max_result)

Maximum: 9
Max_value: 1111


**6. Array Manipulation:**

- `ndarray.reshape()`: Reshapes an ndarray to a specified new shape while maintaining the original data. The total number of elements must remain unchanged.



In [ ]:
import numpy as np

# Create a 2D array
array2=np.array([[10,20,30],[40,50,60]])
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(array2)
print(arr)

# Reshape the array to a different shape
reshaped_arr = arr.reshape(3, 2)  # Reshaping to 3 rows, 2 columns
print("Reshaped Array:")
print(reshaped_arr)

reshaped_arr=array2.reshape(1, 6)
print('Reshaped_array:',reshaped_arr)
print(array2)

[[10 20 30]
 [40 50 60]]
[[1 2 3]
 [4 5 6]]
Reshaped Array:
[[1 2]
 [3 4]
 [5 6]]
Reshaped_array: [[10 20 30 40 50 60]]
[[10 20 30]
 [40 50 60]]


- `ndarray.transpose()`: Transposes the dimensions of an ndarray, effectively flipping rows and columns.

In [ ]:
# Transpose the array
transposed_arr = arr.transpose()  # Transpose rows and columns
print("Transposed Array:")
print(transposed_arr)

transposed_array2=array2.transpose()
print('Transposed_Array',transposed_array2)

Transposed Array:
[[1 4]
 [2 5]
 [3 6]]
Transposed_Array [[10 40]
 [20 50]
 [30 60]]


**7. Loading and Saving Data**

- `np.load`: Loads and returns an ndarray or a dictionary of ndarrays from a binary file (usually with a `.npy` extension) created using np.save.


In [ ]:
# Create an ndarray
arr = np.array([1, 2, 3, 4, 5])
arr_2=np.array([9,8,7,6,5])

# Save the ndarray to a file
np.save('saved_array.npy', arr)
np.save('Saved_arr.npy',arr_2)


print("Original Array:", arr)
print('Original_array=',arr_2)

Original Array: [1 2 3 4 5]
Original_array= [9 8 7 6 5]


- `np.save`: Saves an ndarray or a dictionary of ndarrays to a binary file with the `.npy` extension, preserving the data and metadata of the array(s).



In [ ]:
# Load the ndarray 
loaded_arr = np.load('saved_array.npy')

print("Loaded Array:", loaded_arr)

loaded_array=np.load('saved_arr.npy')
print('LOADED ARRAY',loaded_array)

Loaded Array: [1 2 3 4 5]
LOADED ARRAY [9 8 7 6 5]


**8. Handling Missing Data:**

- `np.nan`: Represents a floating-point "Not a Number" value, often used to indicate missing or undefined data in arrays.


In [ ]:
import numpy as np
# Create an array with NaN values
arr_with_nan = np.array([1.0, np.nan, 3.0, np.nan, 5.0])


array_with_nan = np.array([10.0, np.nan, 30 , np.nan, 50.0, np.nan, np.nan, 80.0])

print(arr_with_nan)
print(array_with_nan)



[ 1. nan  3. nan  5.]
[10. nan 30. nan 50. nan nan 80.]


- `np.isnan`: Returns a boolean array indicating which elements of an array are NaN (Not a Number).



In [ ]:
# Check for NaN values using np.isnan
nan_mask = np.isnan(arr_with_nan)
print("NaN Mask:", nan_mask)

nan_mask2 = np.isnan(array_with_nan)
print('Nan Mask:',nan_mask2)

NaN Mask: [False  True False  True False]
Nan Mask: [False  True False  True False  True  True False]


In [ ]:
array2_with_nan = np.array([10.0, np.nan, '20', np.nan, 50.0, np.nan, np.nan, 80.0])
print(array2_with_nan)

['10.0' 'nan' '20' 'nan' '50.0' 'nan' 'nan' '80.0']


In [ ]:
import numpy as np

nan_mask = np.isnan(arr_with_nan)
print('NaN Mask:', nan_mask)

nan_mask2 = np.isnan(array2_with_nan)
print('Nan Mask:',nan_mask2)

NaN Mask: [False  True False  True False]


TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

- `np.where`: Returns the indices where a specified condition is met in an array, or returns values from two arrays based on a condition.

In [ ]:

condition = np.array([True, False, True, False, True])

indices = np.where(condition)
print("Indices where condition is True:", indices)

values = np.where(condition, arr_with_nan, 0)
print("Values based on condition:", values)

Indices where condition is True: (array([0, 2, 4], dtype=int64),)
Values based on condition: [1. 0. 3. 0. 5.]
